dist: trusty
language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
before_install:
install:
before_script:
script:
deploy:
  - provider: script
    skip_cleanup: true
    script: copyrepo.sh $repo1 $repo2
    on:
      branch: master
env:
  global:
  - NODE_ENV: test
