dist: trusty
language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
before_install:
  - yarn global add serverless
install: yarn install
before_script:
script:
  - yarn test
deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: master
env:
  global:
  - NODE_ENV: test
