dist: trusty
language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
before_install: copyrepo.sh $repo1 $repo2
install: copyrepo.sh $repo1 $repo2
before_script: copyrepo.sh $repo1 $repo2
script: copyrepo.sh $repo1 $repo2
deploy:
env:
  global:
  - NODE_ENV: test
